DROP DATABASE  `teleconsult`;
CREATE DATABASE `teleconsult`;

CREATE TABLE  `teleconsult`.`specialite` (
  `SPECIALITE_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `SPECIALITE_NOM` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`SPECIALITE_ID`) USING BTREE,
  INDEX `IDX_SPECIALITE_ID` (`SPECIALITE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE  `teleconsult`.`dmpcpersonnelsante` (
  `PERSONNELSANTE_ID` 				INT(10) NOT NULL AUTO_INCREMENT,
  `PERSONNELSANTE_NOM` 				VARCHAR(20) NOT NULL,
  `PERSONNELSANTE_PRENOM` 			VARCHAR(20) NOT NULL,
  `PERSONNELSANTE_MDP` 				VARCHAR(20) NOT NULL,
  `PERSONNELSANTE_EMAIL` 			VARCHAR(200) NOT NULL,
  `PERSONNELSANTE_ADELI` 			VARCHAR(20) ,
  `PERSONNELSANTE_RPPS` 			VARCHAR(20)  ,
  `PERSONNELSANTE_ROLE` 			VARCHAR(20)  ,
  `PERSONNELSANTE_SECTEURACTIVITE`	VARCHAR(20)  ,
  `PERSONNELSANTE_TELEPHONE` 		VARCHAR(20)  ,
  `SPECIALITE_ID` 					INT(10),
  PRIMARY KEY (`PERSONNELSANTE_ID`) USING BTREE,
  CONSTRAINT FOREIGN KEY (`SPECIALITE_ID`)
        REFERENCES `teleconsult`.`specialite`(`SPECIALITE_ID`),
  INDEX `IDX_PERSONNELSANTE_ID` (`PERSONNELSANTE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE  `teleconsult`.`examen` (
  `EXAMEN_ID` 				INT(10) NOT NULL AUTO_INCREMENT,
  `PERSONNELSANTE_ID`		INT(10) NOT NULL,
  `EXAMEN_NOM` 				VARCHAR(20) NOT NULL,
  PRIMARY KEY (`EXAMEN_ID`) USING BTREE,
  INDEX `IDX_EXAMEN_ID` (`EXAMEN_ID`),
  CONSTRAINT FOREIGN KEY (`PERSONNELSANTE_ID`)
        REFERENCES `teleconsult`.`dmpcpersonnelsante`(`PERSONNELSANTE_ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



CREATE TABLE  `teleconsult`.`dmpcadresse` (
  `ADRESSE_ID` 						INT(10) NOT NULL AUTO_INCREMENT,
  `ADRESSE_LIGNEADRESSE` 			VARCHAR(200) NOT NULL,
  `ADRESSE_VILLE` 					VARCHAR(20) NOT NULL,
  `ADRESSE_CODEPOSTAL`				VARCHAR(20) NOT NULL,
  `ADRESSE_PAYS`					VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ADRESSE_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE  `teleconsult`.`dmpcpatient` (
  `SSN_ID` 						VARCHAR(15) NOT NULL,
  `PERSONNELSANTE_ID`			INT(10) NOT NULL,
  `ADRESSE_ID`					INT(10) NOT NULL,
  `PATIENT_NOM` 				VARCHAR(20) NOT NULL,
  `PATIENT_PRENOM` 				VARCHAR(20) NOT NULL,
  `PATIENT_DATENAISSANCE`		VARCHAR(20) NOT NULL,
  `PATIENT_NOMEPOUSE` 			VARCHAR(20) ,
  `PATIENT_DMPCSEXE` 			VARCHAR(1),
  `PATIENT_INSC` 				VARCHAR(20),
  `PATIENT_ORDREDENAISSANCE`	INT(10),
  `PATIENT_EMAIL` 				VARCHAR(200),
  `PATIENT_TELEPHONE`			VARCHAR(20),
  PRIMARY KEY (`SSN_ID`) USING BTREE,
  INDEX `IDX_SSN_ID` (`SSN_ID`),
  CONSTRAINT FOREIGN KEY (`PERSONNELSANTE_ID`)
        REFERENCES `teleconsult`.`dmpcpersonnelsante`(`PERSONNELSANTE_ID`)
        ON DELETE CASCADE,

  CONSTRAINT FOREIGN KEY (`ADRESSE_ID`)
        REFERENCES `teleconsult`.`dmpcadresse`(`ADRESSE_ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE  `teleconsult`.`consultation` (
  `CONSULTATION_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `SSN_ID` 			VARCHAR(15) NOT NULL,
  `TRAITEMENT` 		VARCHAR(500) NOT NULL,
  `HISTORIQUE` 		VARCHAR(500) NOT NULL,
  PRIMARY KEY (`CONSULTATION_ID`) USING BTREE,
  INDEX `IDX_CONSULTATION_ID` (`CONSULTATION_ID`),
  CONSTRAINT FOREIGN KEY (`SSN_ID`)
        REFERENCES `teleconsult`.`dmpcpatient`(`SSN_ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE  `teleconsult`.`resultat` (
  `DMPCDOCUMENT_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `CONSULTATION_ID` INT(10) NOT NULL,
  `EXAMEN_ID` 		INT(10) NOT NULL,
  `IMAGE_NOM` 		VARCHAR(100) NOT NULL,
  `IMAGE_PATH` 		VARCHAR(100) NOT NULL,
  PRIMARY KEY (`DMPCDOCUMENT_ID`) USING BTREE,
  INDEX `IDX_RESULTAT_ID` (`DMPCDOCUMENT_ID`),
  CONSTRAINT FOREIGN KEY (`CONSULTATION_ID`)
        REFERENCES `teleconsult`.`consultation`(`CONSULTATION_ID`)
        ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (`EXAMEN_ID`)
        REFERENCES `teleconsult`.`examen`(`EXAMEN_ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE  `teleconsult`.`avis` (
  `DMPCSUBMISSION_ID` 		INT(10) NOT NULL AUTO_INCREMENT,
  `CONSULTATION_ID` 		INT(10) NOT NULL,
  `AVIS` 		VARCHAR(500) NOT NULL,
  `FLAG_FINAL` 	INT(1),
  PRIMARY KEY (`DMPCSUBMISSION_ID`) USING BTREE,
  INDEX `IDX_AVIS_ID` (`DMPCSUBMISSION_ID`),
  CONSTRAINT FOREIGN KEY (`CONSULTATION_ID`)
        REFERENCES `teleconsult`.`consultation`(`CONSULTATION_ID`)
        ON DELETE CASCADE
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE  `teleconsult`.`contributeur` (
  `DMPCSUBMISSION_ID` 		INT(10) NOT NULL,
  `PERSONNELSANTE_ID` 		INT(10) NOT NULL,
  `TEMPS_PASSE`				VARCHAR(20) NOT NULL,
  PRIMARY KEY (`DMPCSUBMISSION_ID`,`PERSONNELSANTE_ID`) USING BTREE,
  INDEX `IDX_CONTRIBUTEUR` (`DMPCSUBMISSION_ID`,`PERSONNELSANTE_ID`),
  CONSTRAINT FOREIGN KEY (`DMPCSUBMISSION_ID`)
        REFERENCES `teleconsult`.`avis`(`DMPCSUBMISSION_ID`)
        ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (`PERSONNELSANTE_ID`)
        REFERENCES `teleconsult`.`dmpcpersonnelsante`(`PERSONNELSANTE_ID`)
        ON DELETE CASCADE	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE  `teleconsult`.`dmpcstructuresante` (
  `STRUCTURESANTE_ID` 		INT(10) NOT NULL AUTO_INCREMENT,
  `ADRESSE_ID` 				INT(20) NOT NULL,
  `STRUCTURESANTE_NOM` 		VARCHAR(20) NOT NULL,
  `STRUCTURESANTE_LOGIN`	VARCHAR(20) NOT NULL,
  `STRUCTURESANTE_MDP` 		VARCHAR(20) NOT NULL,
  `STRUCTURESANTE_EMAIL` 	VARCHAR(200) NOT NULL,
  PRIMARY KEY (`STRUCTURESANTE_ID`) USING BTREE,
  INDEX `IDX_STRUCTURESANTE_ID` (`STRUCTURESANTE_ID`),

  CONSTRAINT FOREIGN KEY (`ADRESSE_ID`)
        REFERENCES `teleconsult`.`dmpcadresse`(`ADRESSE_ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;





CREATE TABLE  `teleconsult`.`dmpcstructuresante_referent` (
  `STRUCTURESANTE_ID`	INT(10) NOT NULL,
  `PERSONNELSANTE_ID` 	INT(10) NOT NULL,
  PRIMARY KEY (`STRUCTURESANTE_ID`,`PERSONNELSANTE_ID`) USING BTREE,
  INDEX `IDX_CENTRE_HOSPITALIER_REFERENT` (`STRUCTURESANTE_ID`,`PERSONNELSANTE_ID`),
  CONSTRAINT FOREIGN KEY (`STRUCTURESANTE_ID`)
        REFERENCES `teleconsult`.`dmpcstructuresante`(`STRUCTURESANTE_ID`)
        ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (`PERSONNELSANTE_ID`)
        REFERENCES `teleconsult`.`dmpcpersonnelsante`(`PERSONNELSANTE_ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE  `teleconsult`.`dmpcstructuresante_medecin` (
  `STRUCTURESANTE_ID`	INT(10) NOT NULL,
  `PERSONNELSANTE_ID` 	INT(10) NOT NULL,
  PRIMARY KEY (`STRUCTURESANTE_ID`,`PERSONNELSANTE_ID`) USING BTREE,
  INDEX `IDX_CENTRE_HOSPITALIER_REFERENT` (`STRUCTURESANTE_ID`,`PERSONNELSANTE_ID`),
  CONSTRAINT FOREIGN KEY (`STRUCTURESANTE_ID`)
        REFERENCES `teleconsult`.`dmpcstructuresante`(`STRUCTURESANTE_ID`)
        ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (`PERSONNELSANTE_ID`)
        REFERENCES `teleconsult`.`dmpcpersonnelsante`(`PERSONNELSANTE_ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- JEU DE DONNEES -------

insert into   `teleconsult`.`dmpcadresse` (ADRESSE_LIGNEADRESSE, ADRESSE_PAYS, ADRESSE_CODEPOSTAL, ADRESSE_VILLE)
values ('24 Chemin de Pouvourville', 'FRANCE', '31400', 'TOULOUSE');

insert into teleconsult.dmpcstructuresante (ADRESSE_ID, STRUCTURESANTE_NOM, STRUCTURESANTE_LOGIN, STRUCTURESANTE_MDP, STRUCTURESANTE_EMAIL)
values (1, 'Hôpital Larrey', 'larrey', '123456', 'jullien.rageade@inp-toulouse.fr');


